SRC_NAME = 	main.cpp\
			Contact.class.cpp\

NAME = phonebook

CC = clang++

FLAGS = -Wall -Wextra -Werror

all :
	$(CC) $(FLAGS) $(SRC_NAME) -o $(NAME)

clean:
	rm $(NAME)

fclean: clean

re: fclean all